// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA21AzOjlLoNQAU6zio8jHLXUx89Lu553E',
    appId: '1:256808919619:web:ec5819d647c9c8ea2faaf6',
    messagingSenderId: '256808919619',
    projectId: 'taskhive-21eb8',
    authDomain: 'taskhive-21eb8.firebaseapp.com',
    storageBucket: 'taskhive-21eb8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0RjJkD9xzjki5l4A2_COAaGUUEUAK5G0',
    appId: '1:256808919619:ios:843ded9b77103d842faaf6',
    messagingSenderId: '256808919619',
    projectId: 'taskhive-21eb8',
    storageBucket: 'taskhive-21eb8.firebasestorage.app',
    iosBundleId: 'com.example.commonw',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0RjJkD9xzjki5l4A2_COAaGUUEUAK5G0',
    appId: '1:256808919619:ios:843ded9b77103d842faaf6',
    messagingSenderId: '256808919619',
    projectId: 'taskhive-21eb8',
    storageBucket: 'taskhive-21eb8.firebasestorage.app',
    iosBundleId: 'com.example.commonw',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA21AzOjlLoNQAU6zio8jHLXUx89Lu553E',
    appId: '1:256808919619:web:c35d17c6668162b72faaf6',
    messagingSenderId: '256808919619',
    projectId: 'taskhive-21eb8',
    authDomain: 'taskhive-21eb8.firebaseapp.com',
    storageBucket: 'taskhive-21eb8.firebasestorage.app',
  );

}